const sfs = {

    "aggregation_descriptor": {
        "twelvemonthrolling": "Aggregation over advancing time intervals of 12 months.",
        "daily": "Produced or occurring every day or every weekday.",
        "monthly": "Produced or occurring every month.",
        "upperband": "the upper bound of a range in aggregated data"
    },

    "aggregation": {
        "average": "Average value (e.g. average_zone_air_temperature_sensor)",
        "max": "Maximum value (e.g. Max_Cooling_Air_Flow_Setpoint)",
        "min": "Minimum value (e.g. Min_Ventilation_Air_Flow_Setpoint)",
        "total": "Sum total of some set of values (e.g. total_request_heating_count)",
        "mean": "Average of the set of values in a sample of data"
    },

    "component": {
        "battery": "A device used to store power for use at a later time (e.g. in an emergency where grid power is unavailable).",
        "cable": "A length of wire, sometimes shielded externally, used for some purpose (e.g. steel braided wire for tensile support, CAT5 cable for communications, etc.).",
        "coil": "Component that exchanges heat between two media streams.",
        "compressor": "Component which drives refrigerant compression (and thus cooling processes) within a device or system.",
        "condenser": "The component of a refrigeration system that condenses refrigerant.",
        "controller": "Control loop, such as a PID controller.",
        "cooler": "Device used to cool product (e.g. walk-in food cooler) or media.",
        "damper": "Component which meters the flow of air within a system or device.",
        "dehumidifier": "Device used to dehumidify air.",
        "device": "The core equipment being represented by the Field groupings.",
        "dial": "Adjustment device (e.g. setpoint dial).",
        "dimmer": "A device which can reduce lighting output of a lamp (thus \"dimming\" the light).",
        "dishwasher": "Device that washes dishes.",
        "dryer": "A component used for drying clothes.",
        "evaporator": "The component of a refrigeration system that evaporates refrigerant.",
        "fan": "Component used for the distribution of air.",
        "filter": "Component used for removing dust and other particulate matter from the air.",
        "guidevane": "Control vanes that meter refrigerant (on a centrifugal chiller) or air (on an AHU).",
        "heater": "Component which provides heat to media.",
        "humidifier": "Component which humidifies.",
        "lamp": "The component of a lighting device that emits the light.",
        "pump": "Component used for the distribution of liquid media.",
        "shade": "Window covering.",
        "tank": "Storage device for media.",
        "valve": "Component which meters the flow of water within a system or device.",
        "vane": "Component for guiding media flow.",
        "wheel": "Component used for transfer of heat from incoming to outgoing air streams.",
        "sump": "Low space that collects liquids such as water or chemicals.",
        "radiator": "Component that emits heat by radiation",
        "header": "Distribution pipe.",
        "glass": "TBD.",
        "frame": "TBD.",
        "wemsfilm": "TBD.",
        "audio": "A critical component of multimedia systems, communication devices, and entertainment systems, responsible for the capture, transmission, and reproduction of sound.",
        "screen": "A visual display component used to present graphical or textual information to users",
        "commuters": "Commuters are individuals who travel using various modes of transportation like cars, buses, trains, bicycles, and walking.",
        "cpu": "central processing unit; the primary component of a computer that processes instructions.",
        "heap": "Stores information, such as data and programs, for immediate use in the computer.",
        "storagedrive": "An internal or external computer component that stores data, such as operating systems, applications, and user files.",
        "dispenser": "Dispenser for Sanitation Device"
    },

    "descriptor": {
        "air": "Atmospheric air, either conditioned or unconditioned",
        "aisle": "Passage between two rows of server racks.",
        "external": "TBD.",
        "internal": "TBD.",
        "blowdown": "Process of expelling water filled with mineral deposits for the purposes of water treatment. ",
        "boost": "Component used to boost pressure.",
        "broken": "A state of disrepair; fractured or segmented.",
        "building": "Applies to the entire building or group of zones within building (e.g. Building_Air_Static_Pressure_Sensor)",
        "bypass": "Route which fluid takes to bypass process.",
        "calendar": "A system structured around the days, weeks, and the months, used to manage schedules.",
        "call": "An action of speaking or meeting among multiple people.",
        "chilled": "Cold water (typically 40 - 50F)",
        "circulation": "Process or component used to circulate fluid through a device or system (typically onboard a boiler).",
        "co": "Measures carbon monoxide concentration.",
        "co2": "Measures carbon dioxide concentration.",
        "cogeneration": "Associated with a cogeneration process.",
        "cold": "Associated with cold area or process.",
        "condensing": "Process of gaseous refrigerant changing to liquid.",
        "conference": "An instance of speaking or meeting among multiple people.",
        "control": "The process of governing the actions of a device.",
        "cooling": "Process, measured effect or requirement for cooling.",
        "subcooling": "Lowering in temperature of the liquid refrigerant in the condenser coil",
        "dehumidification": "Process of removing moisture from air.",
        "detection": "Process of identifying conditions.",
        "discharge": "Media leaving system to enter ambient conditioned space. Typically applies only to air-side systems.",
        "east": "Cardinal direction; opposite of west",
        "economizer": "Process or component responsible for the utilization of free cooling.",
        "electric": "Process or component driven by electricity (as to distinguish from natural gas, for instance).",
        "email": "A unique identifier address in the Internet.",
        "emergency": "a situation that poses an immediate risk to health, life property,  or environment.",
        "entering": " The process of going into a thing (e.g. entering a heat exchanger).",
        "evaporative": "Process associated with the evaporation of water.",
        "event": "A thing of occassion that happens.",
        "exchange": "the transfer of heat from one fluid stream to another.",
        "exercise": "Mode of running equipment to maintain functionality (\"exercise mode\")",
        "exhaust": "Process or component used in the removal of air from a conditioned system to the outside atmosphere.",
        "fabric": "Textile material.",
        "fire": "a potential to cause physical damage through burning",
        "flue": "Chimney for conveying exhaust gas.",
        "demand": "applied to points which calculate need for a process to happen",
        "gas": "Process or component driven by natural gas (as to distinguish from electric).",
        "foam": "a mass of small bubbles formed on or in liquid, typically by agitation or fermentation.",
        "glycol": "Liquid mixture consisting of glycol and water ",
        "guide": "Component used to guide flow of media or movement of component.",
        "hash": "A computed value that is converted from an original value.",
        "heating": "Process, measured effect or requirement for heating.",
        "heat": "Quality of media indicating energy .",
        "preheat": "Heating process to prevent below-freezing air to enter the unit and cause ice.",
        "high": "Level of control or measurement; above medium and low; opposite of low.",
        "hot": "Associated with hot area or process.",
        "humidification": "Process of adding moisture to air.",
        "id": "An identification or identifier.",
        "inlet": "Area of media entrance.",
        "input": "The input to a system.",
        "inter": "Represents something in between references (e.g. average_inter_line_voltage, the average voltage between lines).",
        "isolation": "Process of isolating one component or process from another.",
        "leak": "Media leaving the system abnormally.",
        "leaving": "Area where media leaves process.",
        "limit": "A boundary condition for a control (e.g. low limit).",
        "line": "Refers to the incoming electrical feed (e.g. line current).",
        "loop": "Recirculating loop.",
        "low": "Level of control or measurement; below medium and high; opposite of high.",
        "makeup": "Process of adding ('making-up') water that has been lost due to blowdown or evaporation.",
        "manufacturer": "The company which produces the asset or device.",
        "matched": "A collection of things that are put together as being equal, similar, or complementary.",
        "master": "Highest priority (or primary control) device, sensor, etc.",
        "medium": "Level of control or measurement; between high and low.",
        "message": "A communication sent to or left for a recipient.",
        "mixed": "Process or component used to mix multiple streams of air.",
        "mixing": "Process of mixing substance.",
        "model": "Particular design version of an asset (e.g. model_label).",
        "neutral": "Line in the electrical cirucit which carries current back to the source. Distinct from ground.",
        "next": "Something that occurs directly in time after the present or most recent one.",
        "no2": "Nitrogen dioxide.",
        "no": "Nitrogen monoxide.",
        "hcho": "Formaldehyde",
        "tvoc": "Total Volatile Organic Compounds",
        "o3": "Ozone",
        "nh3": "Ammonia",
        "pm1": "Particulate Matter 1µm",
        "pm4": "Particulate Matter 4µm",
        "pm25": "Particulate Matter 2.5µm",
        "pm10": "Particulate Matter 10µm",
        "north": "Cardinal direction; opposite of south",
        "occupancy": "State of being occupied.",
        "occupied": "State of being within scheduled (time of day or week) run-time parameters.",
        "ongoing": "Hapenning currently, right now.",
        "output": "The output of a control loop (e.g. PID Loop Output)",
        "particle": "A very fine clump of solid matter.",
        "outside": "Process or measurement of local atmospheric conditions.",
        "phase1": "The first (nominally A) phase of three-phase power distribution systems.",
        "phase2": "The second (nominally B) phase of three-phase power distribution systems.",
        "phase3": "The third (nominally C) phase of three-phase power distribution systems.",
        "photocatalyst": "a material that uses absorbed light energy (usually UV) to drive desired reactions that would not otherwise proceed under ambient conditions",
        "preheating": "Process of preheating.",
        "pressurization": "Relating to the level of pressure in a system or vessel.",
        "primary": "Associated with the primary (production) loop of a production process.",
        "process": "Act of processing.",
        "production": "The loop in a system that is responsible for the conditioning of fluid.",
        "protection": "Act of preventing damage to object.",
        "reactive": "Power that is returned to the source (not consumed by the load).",
        "recovery": "Component or process used for the reclamation of heat.",
        "release": "To free from constraints (e.g. to release the door from its magnetic lock).",
        "refrigerant": "Substance used in the mechanical refrigeration process (e.g. R-134a)",
        "request": "A signal from a system device that calls for more of a particular conditioning process (e.g. pressure requests from terminal units).",
        "return": "Measurement or process of media as it is returned from the end-use equipment within the system.",
        "reversing": "Reverses direction of flow (e.g. reversing valve on heat pump).",
        "room": "A space that can be occupied, or a part or division of a building or floor enclosed by walls.",
        "scene": "The holistic ambience achieved from coordinated control of an area\"s lighting levels and colors. One of many stored setpoints that may be recalled to apply predetermined lighting levels across a number of fixtures.",
        "schedule": "Refers to the time-of-day run-time requirements for the equipment.",
        "season": "Weather conditions under which certain systems or processes are enabled.",
        "secondary": "Associated with the secondary (distribution) loop of a produciton process.",
        "seismic": "Related to seismic activity (such as seismic gas shutoff valves).",
        "side": "Position relative to an an object.",
        "smoke": "Visible, suspended particles created during a fire.",
        "source": "The upstream source of conditioning (used specifically for heat exchangers).",
        "south": "Cardinal direction; opposite of north",
        "southeast": "Inter-cardinal direction between South and East.",
        "southwest": "Inter-cardinal direction between South and West.",
        "spray": "Spray of water through air.",
        "stage": "Discrete step (stage) of device activity (such as heating and cooling outputs).",
        "steam": "Water in gaseous form.",
        "suction": "The production of a partial vacuum in order to force fluid into a vacant space (such as refrigerant in a compressor).",
        "summer": "Method or process used during warmer weather (i.e. summer season).",
        "supply": "Measurement or process of media as it is supplied to the end-use equipment within the system.",
        "suppression": "a range of firefighting tactics used to suppress fire",
        "sweeper": "Action performed in a sump to prevent sediment build-up via water turbulence.",
        "sync": "The simultaneous operation or activity of two or more things.",
        "tertiary": "Associated with the tertiary (peripheral) loops of a production process.",
        "ultraviolet": "A short wavelength type of light that is beyond the visible spectrum. It is damaging to DNA and cells, and is commonly used to sterilize surfaces.",
        "unoccupied": "State of being outside of scheduled (time of day or week) run-time parameters.",
        "use": "A descriptor for how the entity in question is used (e.g. zone_use_label = \"office\") ",
        "user": "A person who uses or operates something.",
        "ventilation": "Process used to provide fresh air into a system or zone. ",
        "voc": "Measures volatile organic component concentration.",
        "water": "Water in liquid form, conditioned or unconditioned",
        "oil": "Viscous liquid derived from petroleum, especially for use as a fuel or lubricant.",
        "west": "Cardinal direction; opposite of east",
        "wind": "Movement of ambient air.",
        "winter": "Method or process used during colder weather (i.e. winter season).",
        "zone": "Region of building which is conditioned.",
        "slab": "A large, thick, flat piece of stone, concrete, or wood, typically rectangular",
        "inverter": "Compressor modulating unit",
        "vfd": "Variable frequency drive",
        "floor": "The lower surface of a room, on which one may walk",
        "liquid": "High-pressure refrigerant gas at a moderate temperature",
        "expansion": "Process of expanding to a lower pressure and greater volume",
        "supplemental": "Process of providing additional heating or heating only specific areas of a zone. Also alias for perimeter.",
        "purge": "Process of removing air and other non-condensables from the refrigeration system",
        "priority": "Order in which we should resolve a defect",
        "storm": "A violent disturbance of the atmosphere with strong winds and usually rain, thunder, lightning, or snow.",
        "idle": "Running without purpose or effect",
        "reset": "Cause (a binary device) to enter the state representing the numeral 0.",
        "leadlag": "Describes the situation where one (leading) variable is cross-correlated with the values of another (lagging) variable at later times",
        "previous": "Event that has occurred directly in time before the present one.",
        "fault": "A condition that causes the device to fail to perform its required function.",
        "supervisory": "A system, process, or equipment that is monitored by the control unit",
        "domestic": "Domestic water supplied through the pipes of the water system of the Town.",
        "balancing": "Establish appropriate proportions of a certain variable of interest.",
        "defrost": "Free of accumulated ice or snow.",
        "central": "Used in context of central distribution",
        "deck": "Isolated section within a duct work",
        "ground": "Reference point in an electrical circuit from which voltages are measured, a common return path for electric current, or a direct physical connection to the earth.",
        "fuel": "Any material that can be made to react with other substances so that it releases energy as heat energy or to be used for work. ",
        "threshold": "The level or point at which you start to experience something, or at which something starts to happen",
        "people": "CUSTOM SUBFIELD TBD",
        "door": "CUSTOM SUBFIELD TBD",
        "lock": "CUSTOM SUBFIELD TBD",
        "window": "CUSTOM SUBFIELD TBD",
        "satisfaction": "CUSTOM SUBFIELD TBD",
        "change": "CUSTOM SUBFIELD TBD",
        "single": "CUSTOM SUBFIELD TBD",
        "object": "CUSTOM SUBFIELD TBD",
        "blocked": "Locker blocked",
        "reactivation": "Processed Air used to remove Moisture from the Wheel",
        "pyranometer": "measuring solar irradiance on a planar surface designed to measure the solar radiation flux density (W/m2) from the hemisphere above within a wavelength range 0.3 μm to 3 μm.",
        "pyrgeometer": "measuring near-surface infra-red radiation spectrum in the wavelength spectrum approximately from 4.5 μm to 100 μm",
        "insulated": "CUSTOM SUBFIELD TBD",
        "communication": "CUSTOM SUBFIELD TBD",
        "hvac": "Heating Ventilation and Air Conditioning",
        "virtual": "not physically existing as such but made by software to appear to do so",
        "connection": "a link between two entities",
        "precipitation": "Product of the condensation of atmospheric water vapor that falls under gravitational pull from clouds",
        "cloud": "A visible mass of condensed water vapor floating in the atmosphere, typically high above the ground",
        "soil": "Soil",
        "minerals": "Minerals",
        "multiplier": "Scaling factor.",
        "person": "Person.",
        "truck": "Truck.",
        "bus": "Bus.",
        "bicycle": "Bicycle.",
        "bike": "Bike.",
        "motorcycle": "Motorcycle.",
        "car": "Car.",
        "o2": "O2.",
        "standby": "Stand by.",
        "combustion": "Combustion",
        "signal": "An electric current or electromagnetic field used to convey data from one device to another.",
        "strength": "Relative quality and/or intensity.",
        "override": "An action that interrupts, cancels, or changes the current action or status.",
        "local": "A definite spatial location involving only a subset of the larger surrounding area.",
        "face": "To be or turn in a particular direction.",
        "import": "Received into a system (i.e. from a utility).",
        "export": "Supplied out of a system (i.e. to a utility).",
        "forecast": "A prediction based on some known sample of time-series data that, due to the volitile nature of its input data, can only output quality data for a limited time frame (i.e. weather forecasting).",
        "tomorrow": "tomorrow",
        "redox": "ORP, or oxidation-reduced potential, measures the pool water’s ability to break down contaminants.",
        "chlorine": "Chlorine is a chemical element; it has symbol Cl and atomic number 17.",
        "acidity": "acidity",
        "calculated": "To determine by mathematical processes.",
        "startup": "Event of engaging a device or equipment.",
        "electrical": "Relating to or associated with electricity.",
        "refill": "Refill"
    },

    "measurement": {
        "concentration": "Concentration of chemical (usually in parts per million or parts per billion).",
        "current": "Flow of electric charge.",
        "energy": " The quantitative property that must be transferred to an object to perform work (default electrical unless otherwise modified).",
        "flux": "Energyflowrate per area",
        "flowrate": "Rate of fluid movement.",
        "frequency": "The rate of cycling within a process. Typically used to describe voltage (and amperage) oscillation within AC power distribution components.",
        "humidity": "Concentration of water vapor in air (conditioned or unconditioned).",
        "illuminance": "Measurement of light.",
        "level": "The height of something with regard to a datum (e.g. the water level of a tank relative to the bottom).",
        "linearvelocity": "Example: wind speed",
        "percentage": "Measurement per hundred.",
        "powerfactor": "Ratio of real and apparent power.",
        "power": "Rate of energy consumption (assumed context is electrical and real, unless otherwise modified).",
        "pressure": "Measured force per unit area within a system or process.",
        "resistance": "Electrical resistance.",
        "specificenthalpy": "Measure of energy of air per unit mass.",
        "temperature": "Measures the temperature of media within a process or system.",
        "voltage": "Electrical potential difference between two reference points.",
        "volume": "The quantity of three-dimensional space contained by a closed surface.",
        "time": "CUSTOM SUBFIELD TBD",
        "angle": "CUSTOM SUBFIELD TBD",
        "luminescence": "CUSTOM SUBFIELD TBD",
        "angularvelocity": "CUSTOM SUBFIELD TBD",
        "massflowrate": "CUSTOM SUBFIELD TBD",
        "mass": "CUSTOM SUBFIELD TBD",
        "noise": "CUSTOM SUBFIELD TBD",
        "cost": "CUSTOM SUBFIELD TBD",
        "pH": "pH is a logarithmic scale used to specify the acidity or basicity of aqueous solutions."
    },

    "measurement_descriptor": {
        "absolute": "Quality of media with respect to non-relativistic boudaries (e.g. absolute temperature).",
        "apparent": "The combination of reactive and real components (power).",
        "brightness": "Giving out or reflecting light; overall level of light in a space.",
        "charge": "The state of power storage (e.g. charged, not charged, discharged, etc.)",
        "closed": "Indicates full closed (for two-position actuators)",
        "deadband": "Represents a range in which the controller does not do anything.",
        "dewpoint": "The thermodynamic point at which water condenses from standing air.",
        "differential": "Measured difference between two reference points (e.g. differential_water_pressure)",
        "efficiency": "The ratio of required input to actual output. ",
        "end": "Indicates a final part of something, especially a period of time.",
        "extent": "Distance travelled.",
        "failed": "Indicates that a point is not operating as intended or is incapable of operating.",
        "lost": "Indicates that a point has lost some quality or quantity inadvertently.",
        "match": "A function that matches something against others.",
        "motion": "Detectable movement of a thing.",
        "index": "An integer which indicates the location of a particular data point in a list or numbered set (e.g. index 1 of [\"a\",\"b\",\"c\"] would return \"b\", assuming the indexing starts at 0).",
        "offset": "The amount or distance by which something is out of line",
        "open": "Indicates full open (for two-position actuators).  This is the default sense if unspecified",
        "thermocouple": "Descriptor on the way the temperature is measured.",
        "position": "A particular way in which something is placed or arranged, such as a door in the open position.",
        "relative": "Quality of media with respect to theoretical minimum or maximum value for a given condition (e.g. relative humidity).",
        "run": "State of being active or operating. By default applies to control program for system (eg VAV program run_command).",
        "saturation": "Point at which no more of a material can be absorbed into another material.",
        "speed": "Numeric setting of how fast to run a device, in the specified untis. Typically used to describe revolutions of a motor as a fraction of nominal or maximum.",
        "start": "Indicates a point in time or space at which something has its origin or beginning.",
        "static": "Resting or stagnant value (e.g. static_pressure_sensor).",
        "thermal": "Relating to the transfer of heat.",
        "tilt": "Degree of radial rotation.",
        "wetbulb": "Describes air temperature measured at 100% relative humidity (saturation).",
        "solar": "Type of Energy",
        "enable": "State of being enabled to run. First level control",
        "effective": "An arbitrary concept which combines into a single value the effect of multiple measurements",
        "parallel": "Parallel Circuit",
        "nominal": "Value measured under specific conditions",
        "remaining": "Continue to possess a particular quality or fulfill a particular role",
        "up": "An increase or improvement in a specific dimension, aspect, or quantity. It suggests a positive change or augmentation in the context being described",
        "down": "A decrease or reduction in a specific dimension, aspect, or quantity. It suggests a negative change or diminishment in the context being described",
        "mute": "Action of silencing or temporarily disabling the sound output or microphone input of a device, such as a television, radio, phone, or computer",
        "on": " State of actively functioning or powered up. It is ready to perform its intended tasks, and its functionalities are available for use",
        "off": "State of not actively functioning or has been powered down. It is not performing its intended tasks, and its functionalities are temporarily unavailable",
        "net": "Difference between an input and an output.",
        "kinetic": "Of or relating to the motion of material bodies and the forces and energy associated therewith.",
        "mount": "A process by which a computers operating system makes files and directories on a storage device available for users.",
        "load": "Value representing the demand on the operating resources of a system."
    },

    "point_type": {
        "accumulator": "The total accumulated quantity (e.g. total energy accumulated).",
        "alarm": "A point that interprets some input values qualitatively (e.g. as good or bad, normal or in alarm, etc.). Alarms are always binary.",
        "capacity": "A design parameter quantity. Ex: design motor power capacity. Is always a maximum limit.",
        "counter": "Special case of accumulator that assumes integer values and non-dimensional units",
        "command": "The signal given to make an action happen. Defaults to multistate unless given a measurement type",
        "count": "Total count of actions or requests.",
        "label": "Identifying alias for component or system.",
        "mode": "Distinct mode of operation within system. Common example is economizer mode (enabled or disabled).",
        "requirement": "A lower limit design parameter (e.g. minimum flowrate requirement). Is always a lower limit.",
        "sensor": "Component used to measure some quality of a system or process. Can be feedback for an analog command.",
        "setpoint": "Control target of process or system.",
        "status": "The multistate value indicating an observed state in a piece of equipment, often indicating if a command was effected. It is a neutral observation (e.g. no quality judgment of \"good\" or \"bad\"). It also has no units of measurement (therefore if combined with a measurement subfield, it will indicate that the field is the directional status based on some measurement of that type, e.g. power_status equates to an on/off value based on some inference of power).",
        "specification": "The specified design value for a particular operating condition (differential pressure specification).",
        "timestamp": "An instant in time, represented as a numeric offset from the epoch."
    }
}